services:
  deephaven:
    image: ghcr.io/deephaven/server:${VERSION:-latest}
    ports:
      - '${DEEPHAVEN_PORT:-10000}:10000'
    volumes:
      - ./data:/data
    environment:
      - START_OPTS=-Xmx6g -Ddeephaven.application.dir=/data/app.d -DAuthHandlers=io.deephaven.auth.AnonymousAuthenticationHandler
      # -Dauthentication.psk=SQL_TEST